/** Prioridades DSA v1.0.1 — migração não destrutiva e novos recursos. */
const V101={
  VERSAO:'1.0.1',
  ABA_PLANNER:'Planner',
  ABA_REQ_IGREJA:'Requisitos_Igrejas',
  ABA_UNIDADES:'Unidades_Campo',
  ABA_RELATORIOS:'Relatorios_IA',
  PASTA_USUARIOS:'Prioridades DSA_Fotos_Usuarios'
};
const V101_UNIDADES=['Aeroporto','Aldeia','Alenquer','Almeirim','Anapú I','Anapú II','Assurini','Bela Vista','Boa Vista','Brasil Novo','Castelo de Sonhos','Central Altamira','Central Itaituba','Central Santarém','Floresta - Itaituba','Gurupá','IATAI','Interventoria','Jacareacanga','Jardim Altamira','Jardim Santarém','Juruti','Medicilândia','Mojuí dos Campos','Monte Alegre','Moraes Almeida','Mutirão','Nova República','Novo Horizonte','Novo Progresso','Novo Repartimento I','Novo Repartimento II','Novo Repartimento III','Óbidos','Pacajá I','Pacajá II','Piracanã','Placas','Porto de Moz','Premem','Ruropólis','Sentir Mais','Trairão','Uruará','Vila Nova','Vitória do Xingu'];
const V101_MODULOS=['dashboard','priorities','planner','timeline','evidence','reports','requirements','myChurch'];

function configurarV101(){
  configurarPlannerV101_(); configurarRequisitosIgrejaV101_(); configurarUnidadesV101_(); migrarUsuariosV101_(); migrarPerfilIgrejasV101_(); migrarRelatoriosV101_();
  PropertiesService.getScriptProperties().setProperty('PRIORIDADES_VERSION','1.0.1');
  return {ok:true,version:V101.VERSAO};
}
function ensureSheetV101_(name,headers){const ss=SpreadsheetApp.getActive();let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0){sh.getRange(1,1,1,headers.length).setValues([headers]);formatarV83_(sh,headers.length);}else ensureHeadersV101_(sh,headers);return sh}
function ensureHeadersV101_(sh,headers){let cur=sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).getDisplayValues()[0].map(String);headers.forEach(h=>{if(cur.indexOf(h)<0){sh.insertColumnAfter(sh.getLastColumn());sh.getRange(1,sh.getLastColumn()).setValue(h);cur.push(h)}});formatarV83_(sh,sh.getLastColumn())}
function rowsV101_(sh){if(!sh||sh.getLastRow()<2)return[];const v=sh.getDataRange().getDisplayValues(),h=v.shift();return v.filter(r=>r.some(Boolean)).map(r=>{const o={};h.forEach((x,i)=>o[x]=r[i]);return o})}
function rowObjV101_(sh,row){const h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],v=sh.getRange(row,1,1,sh.getLastColumn()).getDisplayValues()[0],o={};h.forEach((x,i)=>o[x]=v[i]);return o}
function setRowByHeadersV101_(sh,row,obj){const h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0];sh.getRange(row,1,1,h.length).setValues([h.map(k=>obj[k]===undefined?'':obj[k])])}
function findRowV101_(sh,colName,value){const h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],idx=h.indexOf(colName);if(idx<0)return null;const f=sh.getRange(2,idx+1,Math.max(1,sh.getLastRow()-1),1).createTextFinder(String(value)).matchEntireCell(true).findNext();return f?f.getRow():null}
function configurarPlannerV101_(){ensureSheetV101_(V101.ABA_PLANNER,['id','igreja','ano','titulo','area','responsavel','prazo','status','criado_em','criado_por','atualizado_em','atualizado_por'])}
function configurarRequisitosIgrejaV101_(){ensureSheetV101_(V101.ABA_REQ_IGREJA,['igreja','codigo_requisito','meta_padrao','ativo','ultima_atualizacao','atualizado_por'])}
function configurarUnidadesV101_(){const sh=ensureSheetV101_(V101.ABA_UNIDADES,['igreja','campo','polo','distrito','ativo']);const existing=new Set(rowsV101_(sh).map(x=>x.igreja));const add=V101_UNIDADES.filter(x=>!existing.has(x)).map(x=>[x,'Missão Oeste do Pará','','',true]);if(add.length)sh.getRange(sh.getLastRow()+1,1,add.length,5).setValues(add)}
function listarUnidadesCampoV101(){configurarUnidadesV101_();return rowsV101_(SpreadsheetApp.getActive().getSheetByName(V101.ABA_UNIDADES)).filter(x=>String(x.ativo).toLowerCase()!=='false')}
function migrarUsuariosV101_(){const sh=SpreadsheetApp.getActive().getSheetByName('Usuarios')||ensureSheetV101_('Usuarios',['id']);ensureHeadersV101_(sh,['id','nome','funcao','area_atuacao','login','senha','ativo','foto_url','foto_file_id','modulos','igrejas','polo','distrito','ultima_atualizacao','atualizado_por']);const rows=rowsV101_(sh);rows.forEach((u,i)=>{const row=i+2,patch={...u};if(!patch.modulos)patch.modulos=V101_MODULOS.join(',');if(!patch.igrejas)patch.igrejas=patch.funcao==='Administrador'||patch.funcao==='Administrador da Missão'||patch.funcao==='Desenvolvedor'?'Todas':(patch.area_atuacao||'');if(patch.funcao==='Administrador da Missão')patch.funcao='Administrador';if(String(patch.login).toLowerCase()==='admin'&&patch.funcao!=='Desenvolvedor')patch.funcao='Desenvolvedor';setRowByHeadersV101_(sh,row,patch)})}
function migrarPerfilIgrejasV101_(){const sh=SpreadsheetApp.getActive().getSheetByName(V84.ABA_PERFIL_IGREJAS)||ensureSheetV101_(V84.ABA_PERFIL_IGREJAS,['igreja']);ensureHeadersV101_(sh,['igreja','quantidade_anciaos','quantidade_familias','quantidade_uapgs','oficiais','primeiro_anciao_diretor','contato_primeiro_anciao_diretor','endereco','email','observacoes','ultima_atualizacao','atualizado_por'])}
function migrarRelatoriosV101_(){ensureSheetV101_(V101.ABA_RELATORIOS,['id','igreja','ano','data_hora','usuario','modelo','resultado_geral','relatorio','dificuldades','editado_em','editado_por'])}
function autenticarV101_(login,senha){const u=rowsV101_(SpreadsheetApp.getActive().getSheetByName('Usuarios')).find(x=>String(x.login).trim().toLowerCase()===String(login).trim().toLowerCase()&&String(x.senha)===String(senha)&&String(x.ativo).toLowerCase()!=='false');return u||null}
function validarSenhaUsuarioV101(login,senha){return !!autenticarV101_(login,senha)}
function exigirSenhaV101_(login,senha){if(!validarSenhaUsuarioV101(login,senha))throw new Error('Senha do usuário ativo inválida.')}
function exigirDevV101_(login,senha){const u=autenticarV101_(login,senha);if(!u||u.funcao!=='Desenvolvedor')throw new Error('Ação exclusiva do Desenvolvedor.')}
function listarUsuariosV101(){migrarUsuariosV101_();return rowsV101_(SpreadsheetApp.getActive().getSheetByName('Usuarios')).map(u=>{u.ativo=String(u.ativo).toLowerCase()!=='false';delete u.senha;return u})}
function salvarUsuarioV101(p){migrarUsuariosV101_();exigirDevV101_(p.usuario_admin,p.senha_admin);const sh=SpreadsheetApp.getActive().getSheetByName('Usuarios'),id=String(p.id||Utilities.getUuid()),row=findRowV101_(sh,'id',id)||sh.getLastRow()+1,old=row<=sh.getLastRow()?rowObjV101_(sh,row):{};if(!String(p.nome||'').trim()||!String(p.login||'').trim())throw new Error('Nome e usuário são obrigatórios.');let fotoUrl=old.foto_url||'',fotoId=old.foto_file_id||'';if(p.foto_base64){const folder=pastaUsuariosV101_(),blob=Utilities.newBlob(Utilities.base64Decode(p.foto_base64),p.foto_mime||'image/jpeg',p.foto_nome||('usuario-'+id+'.jpg')),file=folder.createFile(blob);try{file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(_e){}fotoId=file.getId();fotoUrl='https://drive.google.com/thumbnail?id='+fotoId+'&sz=w500'}const obj={...old,id,nome:p.nome,funcao:p.funcao||'Secretário(a)',area_atuacao:p.area_atuacao||'',login:p.login,senha:String(p.senha||'').trim()?p.senha:(old.senha||''),ativo:String(p.ativo).toLowerCase()!=='false',foto_url:fotoUrl,foto_file_id:fotoId,modulos:p.modulos||V101_MODULOS.join(','),igrejas:p.igrejas||'',polo:p.polo||'',distrito:p.distrito||'',ultima_atualizacao:new Date(),atualizado_por:p.usuario_admin};if(!obj.senha)throw new Error('Informe a senha para o novo usuário.');setRowByHeadersV101_(sh,row,obj);return {ok:true,id}}
function excluirUsuarioV101(p){exigirDevV101_(p.usuario_admin,p.senha_admin);const sh=SpreadsheetApp.getActive().getSheetByName('Usuarios'),row=findRowV101_(sh,'id',p.id);if(!row)return {ok:false};const u=rowObjV101_(sh,row);if(String(u.login)===String(p.usuario_admin))throw new Error('O Desenvolvedor não pode excluir o próprio acesso ativo.');sh.deleteRow(row);return {ok:true}}
function pastaUsuariosV101_(){const it=DriveApp.getFoldersByName(V101.PASTA_USUARIOS);return it.hasNext()?it.next():DriveApp.createFolder(V101.PASTA_USUARIOS)}
function listarPlannerV101(igreja,ano){configurarPlannerV101_();return rowsV101_(SpreadsheetApp.getActive().getSheetByName(V101.ABA_PLANNER)).filter(x=>(!igreja||igreja==='Todas'||x.igreja===igreja)&&(!ano||String(x.ano)===String(ano)))}
function salvarPlannerV101(p){configurarPlannerV101_();if(!p.igreja||p.igreja==='Todas')throw new Error('Selecione uma igreja.');const sh=SpreadsheetApp.getActive().getSheetByName(V101.ABA_PLANNER),id=p.id||Utilities.getUuid(),row=findRowV101_(sh,'id',id)||sh.getLastRow()+1,old=row<=sh.getLastRow()?rowObjV101_(sh,row):{},obj={...old,id,igreja:p.igreja,ano:p.ano||new Date().getFullYear(),titulo:p.titulo||'',area:p.area||'Identidade',responsavel:p.responsavel||'',prazo:p.prazo||'',status:p.status||'Não iniciado',criado_em:old.criado_em||new Date(),criado_por:old.criado_por||p.usuario,atualizado_em:new Date(),atualizado_por:p.usuario};setRowByHeadersV101_(sh,row,obj);return obj}
function excluirPlannerV101(p){exigirSenhaV101_(p.usuario,p.senha);const sh=SpreadsheetApp.getActive().getSheetByName(V101.ABA_PLANNER),row=findRowV101_(sh,'id',p.id);if(!row)return{ok:false};sh.deleteRow(row);return{ok:true}}
function listarRequisitosV101(igreja){const base=listarRequisitosV84(),custom=igreja&&igreja!=='Todas'?rowsV101_(SpreadsheetApp.getActive().getSheetByName(V101.ABA_REQ_IGREJA)).filter(x=>x.igreja===igreja):[],map={};custom.forEach(x=>map[x.codigo_requisito]=x);return base.map(r=>({...r,meta_padrao:map[r.codigo_requisito]?Number(map[r.codigo_requisito].meta_padrao||0):Number(r.meta_padrao||0),ativo:map[r.codigo_requisito]?String(map[r.codigo_requisito].ativo).toLowerCase()!=='false':r.ativo,escopo:map[r.codigo_requisito]?'igreja':'global'}))}
function salvarRequisitoV101(p){if(!p.igreja||p.igreja==='Todas')return salvarRequisitoV84(p);configurarRequisitosIgrejaV101_();const sh=SpreadsheetApp.getActive().getSheetByName(V101.ABA_REQ_IGREJA),key=p.igreja+'|'+p.codigo_requisito,rows=rowsV101_(sh);let row=null;rows.forEach((x,i)=>{if(x.igreja+'|'+x.codigo_requisito===key)row=i+2});row=row||sh.getLastRow()+1;setRowByHeadersV101_(sh,row,{igreja:p.igreja,codigo_requisito:p.codigo_requisito,meta_padrao:Number(p.meta_padrao)||0,ativo:String(p.ativo).toLowerCase()!=='false',ultima_atualizacao:new Date(),atualizado_por:p.usuario});return{ok:true,row,escopo:'igreja'}}
function excluirEvidenciaV101(p){exigirSenhaV101_(p.usuario,p.senha);return excluirEvidenciaV83(p.id)}
function listarEvidenciasV101(igreja){return listarEvidenciasV83(igreja).map(e=>{if(e.file_id&&String(e.mime_type).indexOf('image/')===0)e.url='https://drive.google.com/thumbnail?id='+e.file_id+'&sz=w1600';return e})}
function salvarPerfilIgrejaV101(p){migrarPerfilIgrejasV101_();const sh=SpreadsheetApp.getActive().getSheetByName(V84.ABA_PERFIL_IGREJAS),row=findRowV101_(sh,'igreja',p.igreja)||sh.getLastRow()+1,old=row<=sh.getLastRow()?rowObjV101_(sh,row):{},obj={...old,igreja:p.igreja,quantidade_anciaos:Number(p.quantidade_anciaos)||0,quantidade_familias:Number(p.quantidade_familias)||0,quantidade_uapgs:Number(p.quantidade_uapgs)||0,oficiais:p.oficiais||'',primeiro_anciao_diretor:p.primeiro_anciao_diretor||'',contato_primeiro_anciao_diretor:p.contato_primeiro_anciao_diretor||'',endereco:p.endereco||'',email:p.email||'',observacoes:p.observacoes||'',ultima_atualizacao:new Date(),atualizado_por:p.usuario||''};setRowByHeadersV101_(sh,row,obj);return{ok:true,row}}
function listarRelatoriosV101(igreja,ano){migrarRelatoriosV101_();return rowsV101_(SpreadsheetApp.getActive().getSheetByName(V101.ABA_RELATORIOS)).filter(r=>(!igreja||igreja==='Todas'||r.igreja===igreja)&&(!ano||String(r.ano)===String(ano))).sort((a,b)=>String(b.data_hora).localeCompare(String(a.data_hora)))}
function salvarRelatorioV101(p){migrarRelatoriosV101_();const sh=SpreadsheetApp.getActive().getSheetByName(V101.ABA_RELATORIOS),id=p.id||Utilities.getUuid(),row=findRowV101_(sh,'id',id)||sh.getLastRow()+1,old=row<=sh.getLastRow()?rowObjV101_(sh,row):{},obj={...old,id,igreja:p.igreja||old.igreja,ano:p.ano||old.ano,data_hora:old.data_hora||new Date(),usuario:old.usuario||p.usuario,modelo:old.modelo||'manual',resultado_geral:p.resultado_geral||old.resultado_geral||'',relatorio:p.relatorio||'',dificuldades:p.dificuldades||'',editado_em:new Date(),editado_por:p.usuario||''};setRowByHeadersV101_(sh,row,obj);return obj}
function excluirRelatorioV101(p){exigirSenhaV101_(p.usuario,p.senha);const sh=SpreadsheetApp.getActive().getSheetByName(V101.ABA_RELATORIOS),row=findRowV101_(sh,'id',p.id);if(!row)return{ok:false};sh.deleteRow(row);return{ok:true}}
function autenticarPublicoV101(login,senha){const u=autenticarV101_(login,senha);if(!u)return null;const out={};Object.keys(u).forEach(k=>{if(k!=='senha')out[k]=u[k]});return out}
