/** V8.3 - Estatísticas manuais, texto bíblico diário e evidências */
const V83={ABA_IGREJAS:'Igrejas',ABA_VERSICULOS:'Versiculos_Diarios',ABA_EVIDENCIAS:'Evidencias',PASTA_EVIDENCIAS:'Prioridades Estratégicas - Evidências'};
const V83_TEXTOS=["Tudo quanto fizerdes, fazei-o de todo o coração. — Colossenses 3:23", "Confia no Senhor de todo o teu coração. — Provérbios 3:5", "O Senhor é o meu pastor; nada me faltará. — Salmo 23:1", "Posso todas as coisas naquele que me fortalece. — Filipenses 4:13", "Alegrai-vos na esperança, sede pacientes na tribulação. — Romanos 12:12", "Lâmpada para os meus pés é a tua palavra. — Salmo 119:105", "Buscai primeiro o reino de Deus. — Mateus 6:33", "Sede fortes e corajosos; o Senhor está convosco. — Josué 1:9", "O amor é paciente e bondoso. — 1 Coríntios 13:4", "Entrega o teu caminho ao Senhor e confia nele. — Salmo 37:5", "A fé vem pelo ouvir a Palavra de Cristo. — Romanos 10:17", "Bem-aventurados os pacificadores. — Mateus 5:9", "O Senhor é bom, fortaleza no dia da angústia. — Naum 1:7", "Servi ao Senhor com alegria. — Salmo 100:2", "Deus é o nosso refúgio e fortaleza. — Salmo 46:1", "Não nos cansemos de fazer o bem. — Gálatas 6:9", "A resposta branda desvia o furor. — Provérbios 15:1", "O fruto do Espírito é amor, alegria e paz. — Gálatas 5:22", "Orai sem cessar. — 1 Tessalonicenses 5:17", "Eu sou o caminho, a verdade e a vida. — João 14:6"];
function configurarV83(){configurarIgrejasV83_();configurarVersiculosV83_();configurarEvidenciasV83_();}
function configurarIgrejasV83_(){const ss=SpreadsheetApp.getActive();let sh=ss.getSheetByName(V83.ABA_IGREJAS);if(!sh)sh=ss.insertSheet(V83.ABA_IGREJAS);const old=sh.getDataRange().getDisplayValues(),existing={};if(old.length>1){const h=old[0];old.slice(1).forEach(r=>{const n=r[h.indexOf('igreja')];if(!n)return;const total=Number(r[h.indexOf('total_membros')]||0),ativos=Number(r[h.indexOf('membros_ativos')]||0);existing[n]={frequentes:Number(r[h.indexOf('membros_frequentes')]||ativos||0),nao:Number(r[h.indexOf('membros_nao_frequentes')]||Math.max(0,total-ativos)||0),transferir:Number(r[h.indexOf('membros_a_transferir')]||0),resgatar:Number(r[h.indexOf('membros_a_resgatar')]||0)}})}const headers=['igreja','distrito','ativo','membros_frequentes','membros_nao_frequentes','membros_a_transferir','membros_a_resgatar','ultima_atualizacao','atualizado_por'];sh.clear();sh.getRange(1,1,1,headers.length).setValues([headers]);sh.getRange(2,1,IGREJAS.length,headers.length).setValues(IGREJAS.map(n=>[n,CONFIG.DISTRITO,true,existing[n]?.frequentes||0,existing[n]?.nao||0,existing[n]?.transferir||0,existing[n]?.resgatar||0,new Date(),'configurarV83']));formatarV83_(sh,headers.length)}
function listarEstatisticasIgrejasV83(){return linhasV83_(V83.ABA_IGREJAS).map(o=>{['membros_frequentes','membros_nao_frequentes','membros_a_transferir','membros_a_resgatar'].forEach(k=>o[k]=Number(o[k]||0));return o})}
function salvarEstatisticasIgrejaV83(p){const sh=SpreadsheetApp.getActive().getSheetByName(V83.ABA_IGREJAS),f=sh.getRange('A:A').createTextFinder(String(p.igreja)).matchEntireCell(true).findNext();if(!f)throw new Error('Igreja não encontrada.');const vals=['membros_frequentes','membros_nao_frequentes','membros_a_transferir','membros_a_resgatar'].map(k=>Math.max(0,Number(p[k])||0));sh.getRange(f.getRow(),4,1,6).setValues([[...vals,new Date(),p.usuario||'']]);return {ok:true,igreja:p.igreja}}
function configurarVersiculosV83_(){const ss=SpreadsheetApp.getActive();let sh=ss.getSheetByName(V83.ABA_VERSICULOS);if(!sh)sh=ss.insertSheet(V83.ABA_VERSICULOS);if(sh.getLastRow()>1)return;sh.clear();sh.getRange(1,1,1,2).setValues([['data','texto_biblico']]);const rows=[];for(let y=2026;y<=2030;y++){let d=new Date(y,0,1),i=0;while(d.getFullYear()===y){rows.push([new Date(d),V83_TEXTOS[i%V83_TEXTOS.length]]);d.setDate(d.getDate()+1);i++}}sh.getRange(2,1,rows.length,2).setValues(rows);sh.getRange(2,2,rows.length,1).setFontStyle('italic');sh.getRange(2,1,rows.length,1).setNumberFormat('yyyy-mm-dd');formatarV83_(sh,2)}
function listarVersiculoDiaV83(data){const target=String(data||Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM-dd'));const rows=linhasV83_(V83.ABA_VERSICULOS);return rows.find(r=>normalizarDataV83_(r.data)===target)||rows[0]||{data:target,texto_biblico:''}}
function configurarEvidenciasV83_(){const ss=SpreadsheetApp.getActive();let sh=ss.getSheetByName(V83.ABA_EVIDENCIAS);if(!sh)sh=ss.insertSheet(V83.ABA_EVIDENCIAS);if(sh.getLastRow()===0)sh.getRange(1,1,1,10).setValues([['id','registro_id','igreja','descricao','arquivo','mime_type','url','file_id','data','usuario']]);formatarV83_(sh,10)}
function listarEvidenciasV83(igreja){return linhasV83_(V83.ABA_EVIDENCIAS).filter(e=>!igreja||igreja==='Todas'||e.igreja===igreja)}
function enviarEvidenciaV83(p){const bytes=Utilities.base64Decode(p.base64),blob=Utilities.newBlob(bytes,p.mimeType||'application/octet-stream',p.fileName),folder=pastaV83_(),file=folder.createFile(blob),id=Utilities.getUuid();try{file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(e){}const publicUrl=String(p.mimeType||'').indexOf('image/')===0?'https://drive.google.com/thumbnail?id='+file.getId()+'&sz=w1600':file.getUrl();SpreadsheetApp.getActive().getSheetByName(V83.ABA_EVIDENCIAS).appendRow([id,p.registro_id||'',p.igreja||'',p.descricao||'Evidência',p.fileName,p.mimeType||'',publicUrl,file.getId(),new Date(),p.usuario||'']);return {id,url:publicUrl}}
function salvarEvidenciaV83(p){const sh=SpreadsheetApp.getActive().getSheetByName(V83.ABA_EVIDENCIAS),f=sh.getRange('A:A').createTextFinder(String(p.id)).matchEntireCell(true).findNext();if(!f)throw new Error('Evidência não encontrada.');sh.getRange(f.getRow(),2).setValue(p.registro_id||'');sh.getRange(f.getRow(),4).setValue(p.descricao||'');return {ok:true}}
function excluirEvidenciaV83(id){const sh=SpreadsheetApp.getActive().getSheetByName(V83.ABA_EVIDENCIAS),f=sh.getRange('A:A').createTextFinder(String(id)).matchEntireCell(true).findNext();if(!f)return {ok:false};const fileId=sh.getRange(f.getRow(),8).getDisplayValue();if(fileId){try{DriveApp.getFileById(fileId).setTrashed(true)}catch(e){}}sh.deleteRow(f.getRow());return {ok:true}}
function pastaV83_(){const it=DriveApp.getFoldersByName(V83.PASTA_EVIDENCIAS);return it.hasNext()?it.next():DriveApp.createFolder(V83.PASTA_EVIDENCIAS)}
function linhasV83_(aba){const sh=SpreadsheetApp.getActive().getSheetByName(aba);if(!sh)return[];const v=sh.getDataRange().getDisplayValues(),h=v.shift();return v.filter(r=>r.some(Boolean)).map(r=>{const o={};h.forEach((x,i)=>o[x]=r[i]);return o})}
function normalizarDataV83_(v){const s=String(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const d=new Date(v);return isNaN(d)?s:Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd')}
function formatarV83_(sh,n){sh.setFrozenRows(1);sh.getRange(1,1,1,n).setFontWeight('bold').setBackground('#102534').setFontColor('#fff');sh.autoResizeColumns(1,n)}
